sudo: required
services:
  - docker

before_install:
  - docker build -t paulo1410/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run paulo1410/client-test npm run test -- --coverage
  # -- --coverage  faz com que o teste só rodar 1 vez

after_success:
  - docker build -t paulo1410/multi-client ./client
  - docker build -t paulo1410/multi-nginx ./nginx
  - docker build -t paulo1410/multi-server ./server
  - docker build -t paulo1410/multi-worker ./worker
  # Fazer login no Docker CLI usando variáveis de ambiente do Travis
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  # Depios enviar essas imagens para o Dockerhub
  - docker push paulo1410/multi-client
  - docker push paulo1410/multi-nginx
  - docker push paulo1410/multi-server
  - docker push paulo1410/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-sa-east-1-443406838013"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
